name: Python CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip downloads
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-
        
      - name: Print environment infoo
        env:
         APP_NAME: "github-actions-python-ci"
        run: |
          echo "App: $APP_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "GitHub repo: $GITHUB_REPOSITORY"
          python --version

      - name: Use a secret safely
        env: 
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "Secret is set (but GitHub will hide it in logs)."
          python -c "import os; print('Secret length:', len(os.getenv('MY_SECRET')))"
      
      - name: Generate build version
        id: version
        run: echo "build_version=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT

      - name: Show build version
        run: echo 'Build version is: ${{ steps.version.outputs.build_version }}'
        

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If requirements.txt exists, install it; otherwise just install pytest
          #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q | tee test-output.txt

      - name: Upload test output artifact
        uses: actions/upload-artifact@v4
        with: 
           name: test-output
           path: test-output.txt

      
      